#!/usr/bin/bash
# PREREQS: enable rpmfusion
sudo dnf install gstreamer1-plugins-{bad-\*,good-\*,base} gstreamer1-plugin-openh264 gstreamer1-libav --exclude=gstreamer1-plugins-bad-free-devel
sudo dnf install lame\* --exclude=lame-devel
sudo dnf install intel-media-driver
sudo dnf group upgrade --with-optional Multimedia